spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   # 使用druid数据源
    druid:
      url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root

  #redis 配置
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
      timeout: 10000

#设置开发环境的端口号
server:
  port: 8080


#mybatis配置
#mybatis:
#  config-location: classpath:/mybatis/config/mybatisConfig.xml   #ʹ使用config-location，可以在mybatisConfig.xml配置mybatis属性，减少yml配置
#  mapper-locations: classpath:mybatis/mapper/*Mapper.xml

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  #mybatis-plus配置
    mapper-locations: classpath:/mybatis/mapper/*Mapper.xml
    typeAliasesPackage: com.siec.system.model.po
    global-config:
      db-config:
        #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
        id-type:
        # 默认数据库表下划线命名
        table-underline: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      jdbc-type-for-null: 'null'

#设置sql语句打印级别
logging:
  level:
    com:
      example:
        shiro:
          mapper: debug