spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   # 使用druid数据源
    druid:
      url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root

  #设置开发环境的端口号
server:
  port: 8080